### ISSUE TITLE
ts-node register?

### ISSUE THREAD

**Issue by amcdnl** [pleerock/class-validator#4]
In your gulp file you are doing some interesting evaluating to transform your typescript file on the fly, there is a project that is similar to `babel/register` for typescript called [ts-node](https://github.com/TypeStrong/ts-node)

In your `gulpfile.js` you would just do:

```
require('ts-node/register');
require('gulpfile')
```

**Comment by PLEEROCK** [comment]
looks like this issue should be in the [gulpclass](https://github.com/PLEEROCK/gulpclass) repository? Actually the code in the gulpfile.js is up to user. There are multiple approaches user can use depend of tsc settings he use. I described on the fly compilation because its simple, does not require to install other modules, and simply works. Maybe there should be a section in docs where we can suggest alternative or all approaches he can use

**Comment by amcdnl** [comment]
Good idea :)
