### ISSUE TITLE
Validating specific properties

### ISSUE THREAD

**Issue by Phmager** [pleerock/class-validator#46]
Is it possible to validate only a specific property?

**Comment by TomMarius** [comment]
You could construct an instance of Validator and then use its methods to validate your property if that's an acceptable workaround for you

**Comment by Phmager** [comment]
Would you accept a pull request for this feature?

**Comment by pleerock** [comment]
you can achieve it via [validation groups](https://github.com/pleerock/class-validator#validation-groups). If you want to create PR for this feature it should be complete and cover all scenarios. I believe API should look like this?:

```typescript
validate(photo, {
     validateProperties: {
          "name": true,
          "description": false,
          "files": false,
          "tags": {
               "id": false,
               "name": true,
                .... 
         } 
     }
})
```

**Comment by ak99372** [comment]
This would be quite useful especially when entering new form when validation should kick in for particular changed field (not for the whole form). It would not be feasible to create a group for each field so an option under ValidatorOptions. I think rather than true or false a simpler would be just list field(s) to validate...

`validate(photo, { validateProperties: {"name", "files", "tags"....}})`
